### ISSUE TITLE
Note in read.me files need to be updated

### ISSUE THREAD

**Issue by allenrowand** [MillenniumMachines/RRF-Configs#9]
The notes in the readme files talk about updating touchprobe.g which has been removed. This should probably be changed to discuss adding the touchprobe definition to config.g

**Comment by benagricola** [comment]
There's a `touchprobe.g` file in the common configuration that _should_ end up in the release zip files. Are you not seeing this file included, even though it's all commented out.

**Comment by allenrowand** [comment]
I'll double check when I'm back at the machine. To confirm, are we supposed to uncomment and enter the touch probe config here or add the definition to config.g?

**Comment by allenrowand** [comment]
I was mistaken, closing the issue
